### ISSUE TITLE
TypeError: BaseModel.model_dump_json() got an unexpected keyword argument 'option'

### ISSUE THREAD

**Issue by stephenyaupro2021** [minimaxir/simpleaichat#75] opened 2023-08-30 16:47 UTC
in simpleaichat.py,
![image](https://github.com/minimaxir/simpleaichat/assets/94089429/42e252e0-efc1-4994-8f17-d83f060373d9)

--> 220         return self.default_session.model_dump_json(
    221             exclude={"api_key", "api_url"},
    222             exclude_none=True,
    223             option=orjson.OPT_INDENT_2,
    224         )

TypeError: BaseModel.model_dump_json() got an unexpected keyword argument 'option'

**Comment by Trolann** [comment] 2023-09-02 21:20
Duplicate of #68

**Closed** 2023-09-07 09:26 UTC
